apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-api-service-account
  labels:
    app: edge-api-service-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: edge-api-service-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: edge-api-service-account
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-module-service-account
  labels:
    app: edge-module-service-account
  annotations:
    moduleId: edge-module