apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-api
  labels:
    app: edge-api
spec:
  selector:
    matchLabels:
      app: edge-api
  replicas: 1
  template:
    metadata:
      labels:
        app: edge-api
    spec:
      serviceAccountName: "edge-api-service-account"
      containers:
        - name: edge-api
          image: dmolokanov/edge-api
---
apiVersion: v1
kind: Service
metadata:
  name: edge-api
  labels:
    app: edge-api
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 35000
  selector:
    app: edge-api