[package]
name = "api"
version = "0.1.0"
authors = ["dmolokanov <dmolokanov@users.noreply.github.com>"]
edition = "2018"

[dependencies]
hyper = "0.12.28"
tokio = "0.1.19"
http = "0.1.17"
bytes = "0.4.12"
futures = "0.1.26"
reqwest = "0.9.16"
